update ods_finance_map_relation
set pro_name='AiGate数据库安全网关系统'where material_code='CP010103-00001';
update ods_finance_map_relation
set pro_name='AiGate数据库安全网关系统'where material_code='CP010103-00002';
update ods_finance_map_relation
set pro_name='AiGate数据库安全网关系统'where material_code='CP010103-00003';
update ods_finance_map_relation
set pro_name='AiGate数据库安全网关系统'where material_code='CP010103-00004';
update ods_finance_map_relation
set pro_name='AiGate数据库安全网关系统'where material_code='CP010103-00006';
update ods_finance_map_relation
set pro_name='AiGate数据库安全网关系统'where material_code='CP010103-00008';
update ods_finance_map_relation
set pro_name='明御综合日志审计平台'where material_code='CP010105-00048';
update ods_finance_map_relation
set pro_name='安恒AiNTA流量审计分析系统'where material_code='CP010302-00005';
update ods_finance_map_relation
set pro_name='安恒AiNTA流量审计分析系统'where material_code='CP010302-00008';
update ods_finance_map_relation
set pro_name='明御综合日志审计平台'where material_code='CP010305-00006';
update ods_finance_map_relation
set pro_name='明御APT攻击预警平台'where material_code='CP010305-00012';
update ods_finance_map_relation
set pro_name='明御综合日志审计平台'where material_code='CP030301-00007';
update ods_finance_map_relation
set pro_name='明御APT攻击预警平台'where material_code='CP030301-00013';
update ods_finance_map_relation
set pro_name='明御APT攻击预警平台'where material_code='CP030301-00014';
update ods_finance_map_relation
set pro_name='明御APT攻击预警平台'where material_code='CP030301-00015';
update ods_finance_map_relation
set pro_name='明御APT攻击预警平台'where material_code='CP030301-00016';
update ods_finance_map_relation
set pro_name='AiGate数据库安全网关系统'where material_code='CP030504-00003';
update ods_finance_map_relation
set pro_name='明御APT攻击预警平台'where material_code='CP030513-00021';
update ods_finance_map_relation
set pro_name='AiGate数据库安全网关系统'where material_code='FW030604-00001';
update ods_finance_map_relation
set pro_name='AiGate数据库安全网关系统'where material_code='FW030604-00002';
update ods_finance_map_relation
set pro_name='AiGate数据库安全网关系统'where material_code='FW030604-00003';
update ods_finance_map_relation
set pro_name='AiGate数据库安全网关系统'where material_code='FW030604-00004';
update ods_finance_map_relation
set pro_name='AiGate数据库安全网关系统'where material_code='FW030606-00057';
update ods_finance_map_relation
set pro_name='明御APT攻击预警平台'where material_code='FW030623-00003';
update ods_finance_map_relation
set pro_name='明御APT攻击预警平台'where material_code='FW030623-00027';
update ods_finance_map_relation
set pro_name='明御APT攻击预警平台'where material_code='FW030624-00024';

update ods_finance_map_relation
set pro_id='034'where material_code='CP010103-00001';
update ods_finance_map_relation
set pro_id='034'where material_code='CP010103-00002';
update ods_finance_map_relation
set pro_id='034'where material_code='CP010103-00003';
update ods_finance_map_relation
set pro_id='034'where material_code='CP010103-00004';
update ods_finance_map_relation
set pro_id='034'where material_code='CP010103-00006';
update ods_finance_map_relation
set pro_id='034'where material_code='CP010103-00008';
update ods_finance_map_relation
set pro_id='047'where material_code='CP010105-00048';
update ods_finance_map_relation
set pro_id='042'where material_code='CP010302-00005';
update ods_finance_map_relation
set pro_id='042'where material_code='CP010302-00008';
update ods_finance_map_relation
set pro_id='047'where material_code='CP010305-00006';
update ods_finance_map_relation
set pro_id='052'where material_code='CP010305-00012';
update ods_finance_map_relation
set pro_id='047'where material_code='CP030301-00007';
update ods_finance_map_relation
set pro_id='052'where material_code='CP030301-00013';
update ods_finance_map_relation
set pro_id='052'where material_code='CP030301-00014';
update ods_finance_map_relation
set pro_id='052'where material_code='CP030301-00015';
update ods_finance_map_relation
set pro_id='052'where material_code='CP030301-00016';
update ods_finance_map_relation
set pro_id='034'where material_code='CP030504-00003';
update ods_finance_map_relation
set pro_id='052'where material_code='CP030513-00021';
update ods_finance_map_relation
set pro_id='034'where material_code='FW030604-00001';
update ods_finance_map_relation
set pro_id='034'where material_code='FW030604-00002';
update ods_finance_map_relation
set pro_id='034'where material_code='FW030604-00003';
update ods_finance_map_relation
set pro_id='034'where material_code='FW030604-00004';
update ods_finance_map_relation
set pro_id='034'where material_code='FW030606-00057';
update ods_finance_map_relation
set pro_id='052'where material_code='FW030623-00003';
update ods_finance_map_relation
set pro_id='052'where material_code='FW030623-00027';
update ods_finance_map_relation
set pro_id='052'where material_code='FW030624-00024';

update ods_finance_map_relation
set financial_pro_line_name='数据安全产品线'where material_code='CP010103-00001';
update ods_finance_map_relation
set financial_pro_line_name='数据安全产品线'where material_code='CP010103-00002';
update ods_finance_map_relation
set financial_pro_line_name='数据安全产品线'where material_code='CP010103-00003';
update ods_finance_map_relation
set financial_pro_line_name='数据安全产品线'where material_code='CP010103-00004';
update ods_finance_map_relation
set financial_pro_line_name='数据安全产品线'where material_code='CP010103-00006';
update ods_finance_map_relation
set financial_pro_line_name='数据安全产品线'where material_code='CP010103-00008';
update ods_finance_map_relation
set financial_pro_line_name='日志与流量产品部'where material_code='CP010105-00048';
update ods_finance_map_relation
set financial_pro_line_name='日志与流量产品部'where material_code='CP010302-00005';
update ods_finance_map_relation
set financial_pro_line_name='日志与流量产品部'where material_code='CP010302-00008';
update ods_finance_map_relation
set financial_pro_line_name='日志与流量产品部'where material_code='CP010305-00006';
update ods_finance_map_relation
set financial_pro_line_name='日志与流量产品部'where material_code='CP010305-00012';
update ods_finance_map_relation
set financial_pro_line_name='日志与流量产品部'where material_code='CP030301-00007';
update ods_finance_map_relation
set financial_pro_line_name='日志与流量产品部'where material_code='CP030301-00013';
update ods_finance_map_relation
set financial_pro_line_name='日志与流量产品部'where material_code='CP030301-00014';
update ods_finance_map_relation
set financial_pro_line_name='日志与流量产品部'where material_code='CP030301-00015';
update ods_finance_map_relation
set financial_pro_line_name='日志与流量产品部'where material_code='CP030301-00016';
update ods_finance_map_relation
set financial_pro_line_name='数据安全产品线'where material_code='CP030504-00003';
update ods_finance_map_relation
set financial_pro_line_name='日志与流量产品部'where material_code='CP030513-00021';
update ods_finance_map_relation
set financial_pro_line_name='数据安全产品线'where material_code='FW030604-00001';
update ods_finance_map_relation
set financial_pro_line_name='数据安全产品线'where material_code='FW030604-00002';
update ods_finance_map_relation
set financial_pro_line_name='数据安全产品线'where material_code='FW030604-00003';
update ods_finance_map_relation
set financial_pro_line_name='数据安全产品线'where material_code='FW030604-00004';
update ods_finance_map_relation
set financial_pro_line_name='数据安全产品线'where material_code='FW030606-00057';
update ods_finance_map_relation
set financial_pro_line_name='日志与流量产品部'where material_code='FW030623-00003';
update ods_finance_map_relation
set financial_pro_line_name='日志与流量产品部'where material_code='FW030623-00027';
update ods_finance_map_relation
set financial_pro_line_name='日志与流量产品部'where material_code='FW030624-00024';


update ods_finance_map_relation
set pro_line_id='24'where material_code='CP010103-00001';
update ods_finance_map_relation
set pro_line_id='24'where material_code='CP010103-00002';
update ods_finance_map_relation
set pro_line_id='24'where material_code='CP010103-00003';
update ods_finance_map_relation
set pro_line_id='24'where material_code='CP010103-00004';
update ods_finance_map_relation
set pro_line_id='24'where material_code='CP010103-00006';
update ods_finance_map_relation
set pro_line_id='24'where material_code='CP010103-00008';
update ods_finance_map_relation
set pro_line_id='22'where material_code='CP010105-00048';
update ods_finance_map_relation
set pro_line_id='22'where material_code='CP010302-00005';
update ods_finance_map_relation
set pro_line_id='22'where material_code='CP010302-00008';
update ods_finance_map_relation
set pro_line_id='22'where material_code='CP010305-00006';
update ods_finance_map_relation
set pro_line_id='22'where material_code='CP010305-00012';
update ods_finance_map_relation
set pro_line_id='22'where material_code='CP030301-00007';
update ods_finance_map_relation
set pro_line_id='22'where material_code='CP030301-00013';
update ods_finance_map_relation
set pro_line_id='22'where material_code='CP030301-00014';
update ods_finance_map_relation
set pro_line_id='22'where material_code='CP030301-00015';
update ods_finance_map_relation
set pro_line_id='22'where material_code='CP030301-00016';
update ods_finance_map_relation
set pro_line_id='24'where material_code='CP030504-00003';
update ods_finance_map_relation
set pro_line_id='22'where material_code='CP030513-00021';
update ods_finance_map_relation
set pro_line_id='24'where material_code='FW030604-00001';
update ods_finance_map_relation
set pro_line_id='24'where material_code='FW030604-00002';
update ods_finance_map_relation
set pro_line_id='24'where material_code='FW030604-00003';
update ods_finance_map_relation
set pro_line_id='24'where material_code='FW030604-00004';
update ods_finance_map_relation
set pro_line_id='24'where material_code='FW030606-00057';
update ods_finance_map_relation
set pro_line_id='22'where material_code='FW030623-00003';
update ods_finance_map_relation
set pro_line_id='22'where material_code='FW030623-00027';
update ods_finance_map_relation
set pro_line_id='22'where material_code='FW030624-00024';

    
