select date("collectorReceiptTime"), count(*) from ods_es_xdr_log_detail_dd
                                        group by date("collectorReceiptTime")
                                        limit 10

CREATE INDEX "index_collectorReceiptTime" ON ods_es_xdr_log_detail_dd ("collectorReceiptTime");
CREATE INDEX "index_id" ON ndi_test_ods_es_xdr_log_detail_dd ("id");

select * from ods_es_xdr_log_detail_dd  limit 1


SELECT
     min(id) minVal,
 max(id) maxVal
FROM
  ods_es_xdr_log_detail_dd
WHERE
  date("collectorReceiptTime")=date('2023-04-13')
limit 1

create  table  ods_es_xdr_log_detail_dd
(  id int8 primary key,
    timestamp timestamp,
    "catBehavior" text,
    "catObject" text,
    "catOutcome" text,
    "catSignificance" text,
    "catTechnique" text,
    "collectorReceiptTime" timestamp,
    "dataSubType" text,
    "dataType" text,
    "destPort" text,
    "destSecurityZone" text,
    "deviceCat" text,
    "deviceName" text,
    "deviceProductType" text,
    "deviceReceiptTime" text,
    "deviceSendProductName" text,
    "deviceVersion" text,
    direction text,
    "dnsType" text,
    "endTime" timestamp,
    "etl_engineInfo" text,
    "eventCount" text,
    "eventId" text,
    "interfaceName" text,
    "logSessionId" text,
    "logType" text,
    "machineCode" text,
    message text,
    "productVendorName" text,
    "queryType" text,
    "requestDomain" text,
    severity text,
    "srcGeoLatitude" text,
    "srcGeoLongitude" text,
    "srcGeoRegion" text,
    "srcSecurityZone" text,
    "startTime" timestamp,
    timestamp_baas_internal_sink_process_time timestamp,
    "transProtocol" text,
    "vlanId" text
)

select coalesce()


select pg_size_pretty(pg_relation_size ('ods_es_xdr_log_detail_dd'));



create table
if not EXISTS `ods.dws_tb5`(
    `id` string,
    `timestamp_` string,
    `catbehavior` string,
    `catobject` string,
    `catoutcome` string,
    `catsignificance` string,
    `cattechnique` string,
    `collectorreceipttime` string,
    `datasubtype` string,
    `datatype` string,
    `destport` string,
    `destsecurityzone` string,
    `devicecat` string,
    `devicename` string,
    `deviceproducttype` string,
    `devicereceipttime` string,
    `devicesendproductname` string,
    `deviceversion` string,
    `direction` string,
    `dnstype` string,
    `endtime` string,
    `etl_engineinfo` string,
    `eventcount` string,
    `eventid` string,
    `interfacename` string,
    `logsessionid` string,
    `logtype` string,
    `machinecode` string,
    `message_` string,
    `productvendorname` string,
    `querytype` string,
    `requestdomain` string,
    `severity` string,
    `srcgeolatitude` string,
    `srcgeolongitude` string,
    `srcgeoregion` string,
    `srcsecurityzone` string,
    `starttime` string,
    `timestamp_baas_internal_sink_process_time` string,
    `transprotocol` string,
    `vlanid` string,
    `id_2` string,
    `timestamp_2` string,
    `catbehavior_2` string,
    `catobject_2` string,
    `catoutcome_2` string,
    `catsignificance_2` string,
    `cattechnique_2` string,
    `collectorreceipttime_2` string,
    `datasubtype_2` string,
    `datatype_2` string,
    `destport_2` string,
    `destsecurityzone_2` string,
    `devicecat_2` string,
    `devicename_2` string,
    `deviceproducttype_2` string,
    `devicereceipttime_2` string,
    `devicesendproductname_2` string,
    `deviceversion_2` string,
    `direction_2` string,
    `dnstype_2` string,
    `endtime_2` string,
    `etl_engineinfo_2` string,
    `eventcount_2` string,
    `eventid_2` string,
    `interfacename_2` string,
    `logsessionid_2` string,
    `logtype_2` string,
    `machinecode_2` string,
    `message_2` string,
    `productvendorname_2` string,
    `querytype_2` string,
    `requestdomain_2` string,
    `severity_2` string,
    `srcgeolatitude_2` string,
    `srcgeolongitude_2` string,
    `srcgeoregion_2` string,
    `srcsecurityzone_2` string,
    `starttime_2` string,
    `timestamp_baas_internal_sink_process_time_2` string,
    `transprotocol_2` string,
    `vlanid_2` string,
    `id_3` string,
    `timestamp_3` string,
    `catbehavior_3` string,
    `catobject_3` string,
    `catoutcome_3` string,
    `catsignificance_3` string,
    `cattechnique_3` string,
    `collectorreceipttime_3` string,
    `datasubtype_3` string,
    `datatype_3` string,
    `destport_3` string,
    `destsecurityzone_3` string,
    `devicecat_3` string,
    `devicename_3` string,
    `deviceproducttype_3` string,
    `devicereceipttime_3` string,
    `devicesendproductname_3` string,
    `deviceversion_3` string,
    `direction_3` string,
    `dnstype_3` string,
    `endtime_3` string,
    `etl_engineinfo_3` string,
    `eventcount_3` string,
    `eventid_3` string,
    `interfacename_3` string,
    `logsessionid_3` string,
    `logtype_3` string,
    `machinecode_3` string,
    `message_3` string,
    `productvendorname_3` string,
    `querytype_3` string,
    `requestdomain_3` string,
    `severity_3` string,
    `srcgeolatitude_3` string,
    `srcgeolongitude_3` string,
    `srcgeoregion_3` string,
    `srcsecurityzone_3` string,
    `starttime_3` string,
    `timestamp_baas_internal_sink_process_time_3` string,
    `transprotocol_3` string,
    `vlanid_3` string,
    `id_4` string,
    `timestamp_4` string,
    `catbehavior_4` string,
    `catobject_4` string,
    `catoutcome_4` string,
    `catsignificance_4` string,
    `cattechnique_4` string,
    `collectorreceipttime_4` string,
    `datasubtype_4` string,
    `datatype_4` string,
    `destport_4` string,
    `destsecurityzone_4` string,
    `devicecat_4` string,
    `devicename_4` string,
    `deviceproducttype_4` string,
    `devicereceipttime_4` string,
    `devicesendproductname_4` string,
    `deviceversion_4` string,
    `direction_4` string,
    `dnstype_4` string,
    `endtime_4` string,
    `etl_engineinfo_4` string,
    `eventcount_4` string,
    `eventid_4` string,
    `interfacename_4` string,
    `logsessionid_4` string,
    `logtype_4` string,
    `machinecode_4` string,
    `message_4` string,
    `productvendorname_4` string,
    `querytype_4` string,
    `requestdomain_4` string,
    `severity_4` string,
    `srcgeolatitude_4` string,
    `srcgeolongitude_4` string,
    `srcgeoregion_4` string,
    `srcsecurityzone_4` string,
    `starttime_4` string,
    `timestamp_baas_internal_sink_process_time_4` string,
    `transprotocol_4` string,
    `vlanid_4` string,
    `id_5` string,
    `timestamp_5` string,
    `catbehavior_5` string,
    `catobject_5` string,
    `catoutcome_5` string,
    `catsignificance_5` string,
    `cattechnique_5` string,
    `collectorreceipttime_5` string,
    `datasubtype_5` string,
    `datatype_5` string,
    `destport_5` string,
    `destsecurityzone_5` string,
    `devicecat_5` string,
    `devicename_5` string,
    `deviceproducttype_5` string,
    `devicereceipttime_5` string,
    `devicesendproductname_5` string,
    `deviceversion_5` string,
    `direction_5` string,
    `dnstype_5` string,
    `endtime_5` string,
    `etl_engineinfo_5` string,
    `eventcount_5` string,
    `eventid_5` string,
    `interfacename_5` string,
    `logsessionid_5` string,
    `logtype_5` string,
    `machinecode_5` string,
    `message_5` string,
    `productvendorname_5` string,
    `querytype_5` string,
    `requestdomain_5` string,
    `severity_5` string,
    `srcgeolatitude_5` string,
    `srcgeolongitude_5` string,
    `srcgeoregion_5` string,
    `srcsecurityzone_5` string,
    `starttime_5` string,
    `timestamp_baas_internal_sink_process_time_5` string,
    `transprotocol_5` string,
    `vlanid_5` string,
    `id_6` string,
    `timestamp_6` string,
    `catbehavior_6` string,
    `catobject_6` string,
    `catoutcome_6` string,
    `catsignificance_6` string,
    `cattechnique_6` string,
    `collectorreceipttime_6` string,
    `datasubtype_6` string,
    `datatype_6` string,
    `destport_6` string,
    `destsecurityzone_6` string,
    `devicecat_6` string,
    `devicename_6` string,
    `deviceproducttype_6` string,
    `devicereceipttime_6` string,
    `devicesendproductname_6` string,
    `deviceversion_6` string,
    `direction_6` string,
    `dnstype_6` string,
    `endtime_6` string,
    `etl_engineinfo_6` string,
    `eventcount_6` string,
    `eventid_6` string,
    `interfacename_6` string,
    `logsessionid_6` string,
    `logtype_6` string,
    `machinecode_6` string,
    `message_6` string,
    `productvendorname_6` string,
    `querytype_6` string,
    `requestdomain_6` string,
    `severity_6` string,
    `srcgeolatitude_6` string,
    `srcgeolongitude_6` string,
    `srcgeoregion_6` string,
    `srcsecurityzone_6` string,
    `starttime_6` string,
    `timestamp_baas_internal_sink_process_time_6` string,
    `transprotocol_6` string,
    `vlanid_6` string
  )
  PARTITIONED BY (`ds` STRING) STORED AS HOLODESK;

set hive.exec.dynamic.partition = true;

set argodb.allow.insert.overwrite = true;

set use.linac = false;

INSERT OVERWRITE TABLE `ods.dws_tb5`
select t1.id,
       t1.timestamp,
       t1.catbehavior,
       t1.catobject,
       t1.catoutcome,
       t1.catsignificance,
       t1.cattechnique,
       t1.collectorreceipttime,
       t1.datasubtype,
       t1.datatype,
       t1.destport,
       t1.destsecurityzone,
       t1.devicecat,
       t1.devicename,
       t1.deviceproducttype,
       t1.devicereceipttime,
       t1.devicesendproductname,
       t1.deviceversion,
       t1.direction,
       t1.dnstype,
       t1.endtime,
       t1.etl_engineinfo,
       t1.eventcount,
       t1.eventid,
       t1.interfacename,
       t1.logsessionid,
       t1.logtype,
       t1.machinecode,
       t1.message,
       t1.productvendorname,
       t1.querytype,
       t1.requestdomain,
       t1.severity,
       t1.srcgeolatitude,
       t1.srcgeolongitude,
       t1.srcgeoregion,
       t1.srcsecurityzone,
       t1.starttime,
       t1.timestamp_baas_internal_sink_process_time,
       t1.transprotocol,
       t1.vlanid,
       t2.id_2,
       t2.timestamp_2,
       t2.catbehavior_2,
       t2.catobject_2,
       t2.catoutcome_2,
       t2.catsignificance_2,
       t2.cattechnique_2,
       t2.collectorreceipttime_2,
       t2.datasubtype_2,
       t2.datatype_2,
       t2.destport_2,
       t2.destsecurityzone_2,
       t2.devicecat_2,
       t2.devicename_2,
       t2.deviceproducttype_2,
       t2.devicereceipttime_2,
       t2.devicesendproductname_2,
       t2.deviceversion_2,
       t2.direction_2,
       t2.dnstype_2,
       t2.endtime_2,
       t2.etl_engineinfo_2,
       t2.eventcount_2,
       t2.eventid_2,
       t2.interfacename_2,
       t2.logsessionid_2,
       t2.logtype_2,
       t2.machinecode_2,
       t2.message_2,
       t2.productvendorname_2,
       t2.querytype_2,
       t2.requestdomain_2,
       t2.severity_2,
       t2.srcgeolatitude_2,
       t2.srcgeolongitude_2,
       t2.srcgeoregion_2,
       t2.srcsecurityzone_2,
       t2.starttime_2,
       t2.timestamp_baas_internal_sink_process_time_2,
       t2.transprotocol_2,
       t2.vlanid_2,
       t3.id_3,
       t3.timestamp_3,
       t3.catbehavior_3,
       t3.catobject_3,
       t3.catoutcome_3,
       t3.catsignificance_3,
       t3.cattechnique_3,
       t3.collectorreceipttime_3,
       t3.datasubtype_3,
       t3.datatype_3,
       t3.destport_3,
       t3.destsecurityzone_3,
       t3.devicecat_3,
       t3.devicename_3,
       t3.deviceproducttype_3,
       t3.devicereceipttime_3,
       t3.devicesendproductname_3,
       t3.deviceversion_3,
       t3.direction_3,
       t3.dnstype_3,
       t3.endtime_3,
       t3.etl_engineinfo_3,
       t3.eventcount_3,
       t3.eventid_3,
       t3.interfacename_3,
       t3.logsessionid_3,
       t3.logtype_3,
       t3.machinecode_3,
       t3.message_3,
       t3.productvendorname_3,
       t3.querytype_3,
       t3.requestdomain_3,
       t3.severity_3,
       t3.srcgeolatitude_3,
       t3.srcgeolongitude_3,
       t3.srcgeoregion_3,
       t3.srcsecurityzone_3,
       t3.starttime_3,
       t3.timestamp_baas_internal_sink_process_time_3,
       t3.transprotocol_3,
       t3.vlanid_3,
       t4.id_4,
       t4.timestamp_4,
       t4.catbehavior_4,
       t4.catobject_4,
       t4.catoutcome_4,
       t4.catsignificance_4,
       t4.cattechnique_4,
       t4.collectorreceipttime_4,
       t4.datasubtype_4,
       t4.datatype_4,
       t4.destport_4,
       t4.destsecurityzone_4,
       t4.devicecat_4,
       t4.devicename_4,
       t4.deviceproducttype_4,
       t4.devicereceipttime_4,
       t4.devicesendproductname_4,
       t4.deviceversion_4,
       t4.direction_4,
       t4.dnstype_4,
       t4.endtime_4,
       t4.etl_engineinfo_4,
       t4.eventcount_4,
       t4.eventid_4,
       t4.interfacename_4,
       t4.logsessionid_4,
       t4.logtype_4,
       t4.machinecode_4,
       t4.message_4,
       t4.productvendorname_4,
       t4.querytype_4,
       t4.requestdomain_4,
       t4.severity_4,
       t4.srcgeolatitude_4,
       t4.srcgeolongitude_4,
       t4.srcgeoregion_4,
       t4.srcsecurityzone_4,
       t4.starttime_4,
       t4.timestamp_baas_internal_sink_process_time_4,
       t4.transprotocol_4,
       t4.vlanid_4,
       t5.id_5,
       t5.timestamp_5,
       t5.catbehavior_5,
       t5.catobject_5,
       t5.catoutcome_5,
       t5.catsignificance_5,
       t5.cattechnique_5,
       t5.collectorreceipttime_5,
       t5.datasubtype_5,
       t5.datatype_5,
       t5.destport_5,
       t5.destsecurityzone_5,
       t5.devicecat_5,
       t5.devicename_5,
       t5.deviceproducttype_5,
       t5.devicereceipttime_5,
       t5.devicesendproductname_5,
       t5.deviceversion_5,
       t5.direction_5,
       t5.dnstype_5,
       t5.endtime_5,
       t5.etl_engineinfo_5,
       t5.eventcount_5,
       t5.eventid_5,
       t5.interfacename_5,
       t5.logsessionid_5,
       t5.logtype_5,
       t5.machinecode_5,
       t5.message_5,
       t5.productvendorname_5,
       t5.querytype_5,
       t5.requestdomain_5,
       t5.severity_5,
       t5.srcgeolatitude_5,
       t5.srcgeolongitude_5,
       t5.srcgeoregion_5,
       t5.srcsecurityzone_5,
       t5.starttime_5,
       t5.timestamp_baas_internal_sink_process_time_5,
       t5.transprotocol_5,
       t5.vlanid_5,
       t6.id_6,
       t6.timestamp_6,
       t6.catbehavior_6,
       t6.catobject_6,
       t6.catoutcome_6,
       t6.catsignificance_6,
       t6.cattechnique_6,
       t6.collectorreceipttime_6,
       t6.datasubtype_6,
       t6.datatype_6,
       t6.destport_6,
       t6.destsecurityzone_6,
       t6.devicecat_6,
       t6.devicename_6,
       t6.deviceproducttype_6,
       t6.devicereceipttime_6,
       t6.devicesendproductname_6,
       t6.deviceversion_6,
       t6.direction_6,
       t6.dnstype_6,
       t6.endtime_6,
       t6.etl_engineinfo_6,
       t6.eventcount_6,
       t6.eventid_6,
       t6.interfacename_6,
       t6.logsessionid_6,
       t6.logtype_6,
       t6.machinecode_6,
       t6.message_6,
       t6.productvendorname_6,
       t6.querytype_6,
       t6.requestdomain_6,
       t6.severity_6,
       t6.srcgeolatitude_6,
       t6.srcgeolongitude_6,
       t6.srcgeoregion_6,
       t6.srcsecurityzone_6,
       t6.starttime_6,
       t6.timestamp_baas_internal_sink_process_time_6,
       t6.transprotocol_6,
       t6.vlanid_6,
       ds
from (
       select id,
              timestamp,
              catbehavior,
              catobject,
              catoutcome,
              catsignificance,
              cattechnique,
              collectorreceipttime,
              datasubtype,
              datatype,
              destport,
              destsecurityzone,
              devicecat,
              devicename,
              deviceproducttype,
              devicereceipttime,
              devicesendproductname,
              deviceversion,
              direction,
              dnstype,
              endtime,
              etl_engineinfo,
              eventcount,
              eventid,
              interfacename,
              logsessionid,
              logtype,
              machinecode,
              message,
              productvendorname,
              querytype,
              requestdomain,
              severity,
              srcgeolatitude,
              srcgeolongitude,
              srcgeoregion,
              srcsecurityzone,
              starttime,
              timestamp_baas_internal_sink_process_time,
              transprotocol,
              vlanid,
              ds
       from ods.dwd_tb5
       where ds = cast(
               current_timestamp - INTERVAL '136' DAY as varchar(10)
             )
       union all
       select id,
              timestamp,
              catbehavior,
              catobject,
              catoutcome,
              catsignificance,
              cattechnique,
              collectorreceipttime,
              datasubtype,
              datatype,
              destport,
              destsecurityzone,
              devicecat,
              devicename,
              deviceproducttype,
              devicereceipttime,
              devicesendproductname,
              deviceversion,
              direction,
              dnstype,
              endtime,
              etl_engineinfo,
              eventcount,
              eventid,
              interfacename,
              logsessionid,
              logtype,
              machinecode,
              message,
              productvendorname,
              querytype,
              requestdomain,
              severity,
              srcgeolatitude,
              srcgeolongitude,
              srcgeoregion,
              srcsecurityzone,
              starttime,
              timestamp_baas_internal_sink_process_time,
              transprotocol,
              vlanid,
              ds
       from ods.dwd_tb5
       where ds = cast(
               current_timestamp - INTERVAL '136' DAY as varchar(10)
             )
       union all
       select id,
              timestamp,
              catbehavior,
              catobject,
              catoutcome,
              catsignificance,
              cattechnique,
              collectorreceipttime,
              datasubtype,
              datatype,
              destport,
              destsecurityzone,
              devicecat,
              devicename,
              deviceproducttype,
              devicereceipttime,
              devicesendproductname,
              deviceversion,
              direction,
              dnstype,
              endtime,
              etl_engineinfo,
              eventcount,
              eventid,
              interfacename,
              logsessionid,
              logtype,
              machinecode,
              message,
              productvendorname,
              querytype,
              requestdomain,
              severity,
              srcgeolatitude,
              srcgeolongitude,
              srcgeoregion,
              srcsecurityzone,
              starttime,
              timestamp_baas_internal_sink_process_time,
              transprotocol,
              vlanid,
              ds
       from ods.dwd_tb5
       where ds = cast(
               current_timestamp - INTERVAL '136' DAY as varchar(10)
             )
       union all
       select id,
              timestamp,
              catbehavior,
              catobject,
              catoutcome,
              catsignificance,
              cattechnique,
              collectorreceipttime,
              datasubtype,
              datatype,
              destport,
              destsecurityzone,
              devicecat,
              devicename,
              deviceproducttype,
              devicereceipttime,
              devicesendproductname,
              deviceversion,
              direction,
              dnstype,
              endtime,
              etl_engineinfo,
              eventcount,
              eventid,
              interfacename,
              logsessionid,
              logtype,
              machinecode,
              message,
              productvendorname,
              querytype,
              requestdomain,
              severity,
              srcgeolatitude,
              srcgeolongitude,
              srcgeoregion,
              srcsecurityzone,
              starttime,
              timestamp_baas_internal_sink_process_time,
              transprotocol,
              vlanid,
              ds
       from ods.dwd_tb5
       where ds = cast(
               current_timestamp - INTERVAL '136' DAY as varchar(10)
             )
       union all
       select id,
              timestamp,
              catbehavior,
              catobject,
              catoutcome,
              catsignificance,
              cattechnique,
              collectorreceipttime,
              datasubtype,
              datatype,
              destport,
              destsecurityzone,
              devicecat,
              devicename,
              deviceproducttype,
              devicereceipttime,
              devicesendproductname,
              deviceversion,
              direction,
              dnstype,
              endtime,
              etl_engineinfo,
              eventcount,
              eventid,
              interfacename,
              logsessionid,
              logtype,
              machinecode,
              message,
              productvendorname,
              querytype,
              requestdomain,
              severity,
              srcgeolatitude,
              srcgeolongitude,
              srcgeoregion,
              srcsecurityzone,
              starttime,
              timestamp_baas_internal_sink_process_time,
              transprotocol,
              vlanid,
              ds
       from ods.dwd_tb5
       where ds = cast(
               current_timestamp - INTERVAL '136' DAY as varchar(10)
             )
     ) as t1
     left join (
       select id as id_2,
              timestamp as timestamp_2,
              catbehavior as catbehavior_2,
              catobject as catobject_2,
              catoutcome as catoutcome_2,
              catsignificance as catsignificance_2,
              cattechnique as cattechnique_2,
              collectorreceipttime as collectorreceipttime_2,
              datasubtype as datasubtype_2,
              datatype as datatype_2,
              destport as destport_2,
              destsecurityzone as destsecurityzone_2,
              devicecat as devicecat_2,
              devicename as devicename_2,
              deviceproducttype as deviceproducttype_2,
              devicereceipttime as devicereceipttime_2,
              devicesendproductname as devicesendproductname_2,
              deviceversion as deviceversion_2,
              direction as direction_2,
              dnstype as dnstype_2,
              endtime as endtime_2,
              etl_engineinfo as etl_engineinfo_2,
              eventcount as eventcount_2,
              eventid as eventid_2,
              interfacename as interfacename_2,
              logsessionid as logsessionid_2,
              logtype as logtype_2,
              machinecode as machinecode_2,
              message as message_2,
              productvendorname as productvendorname_2,
              querytype as querytype_2,
              requestdomain as requestdomain_2,
              severity as severity_2,
              srcgeolatitude as srcgeolatitude_2,
              srcgeolongitude as srcgeolongitude_2,
              srcgeoregion as srcgeoregion_2,
              srcsecurityzone as srcsecurityzone_2,
              starttime as starttime_2,
              timestamp_baas_internal_sink_process_time as timestamp_baas_internal_sink_process_time_2,
              transprotocol as transprotocol_2,
              vlanid as vlanid_2
       from ods.dwd_tb5
       where ds = cast(
               current_timestamp - INTERVAL '136' DAY as varchar(10)
             )
     ) as t2 on t1.id = t2.id_2
     left join (
       select id as id_3,
              timestamp as timestamp_3,
              catbehavior as catbehavior_3,
              catobject as catobject_3,
              catoutcome as catoutcome_3,
              catsignificance as catsignificance_3,
              cattechnique as cattechnique_3,
              collectorreceipttime as collectorreceipttime_3,
              datasubtype as datasubtype_3,
              datatype as datatype_3,
              destport as destport_3,
              destsecurityzone as destsecurityzone_3,
              devicecat as devicecat_3,
              devicename as devicename_3,
              deviceproducttype as deviceproducttype_3,
              devicereceipttime as devicereceipttime_3,
              devicesendproductname as devicesendproductname_3,
              deviceversion as deviceversion_3,
              direction as direction_3,
              dnstype as dnstype_3,
              endtime as endtime_3,
              etl_engineinfo as etl_engineinfo_3,
              eventcount as eventcount_3,
              eventid as eventid_3,
              interfacename as interfacename_3,
              logsessionid as logsessionid_3,
              logtype as logtype_3,
              machinecode as machinecode_3,
              message as message_3,
              productvendorname as productvendorname_3,
              querytype as querytype_3,
              requestdomain as requestdomain_3,
              severity as severity_3,
              srcgeolatitude as srcgeolatitude_3,
              srcgeolongitude as srcgeolongitude_3,
              srcgeoregion as srcgeoregion_3,
              srcsecurityzone as srcsecurityzone_3,
              starttime as starttime_3,
              timestamp_baas_internal_sink_process_time as timestamp_baas_internal_sink_process_time_3,
              transprotocol as transprotocol_3,
              vlanid as vlanid_3
       from ods.dwd_tb5
       where ds = cast(
               current_timestamp - INTERVAL '136' DAY as varchar(10)
             )
     ) as t3 on t1.id = t3.id_3
     left join (
       select id as id_4,
              timestamp as timestamp_4,
              catbehavior as catbehavior_4,
              catobject as catobject_4,
              catoutcome as catoutcome_4,
              catsignificance as catsignificance_4,
              cattechnique as cattechnique_4,
              collectorreceipttime as collectorreceipttime_4,
              datasubtype as datasubtype_4,
              datatype as datatype_4,
              destport as destport_4,
              destsecurityzone as destsecurityzone_4,
              devicecat as devicecat_4,
              devicename as devicename_4,
              deviceproducttype as deviceproducttype_4,
              devicereceipttime as devicereceipttime_4,
              devicesendproductname as devicesendproductname_4,
              deviceversion as deviceversion_4,
              direction as direction_4,
              dnstype as dnstype_4,
              endtime as endtime_4,
              etl_engineinfo as etl_engineinfo_4,
              eventcount as eventcount_4,
              eventid as eventid_4,
              interfacename as interfacename_4,
              logsessionid as logsessionid_4,
              logtype as logtype_4,
              machinecode as machinecode_4,
              message as message_4,
              productvendorname as productvendorname_4,
              querytype as querytype_4,
              requestdomain as requestdomain_4,
              severity as severity_4,
              srcgeolatitude as srcgeolatitude_4,
              srcgeolongitude as srcgeolongitude_4,
              srcgeoregion as srcgeoregion_4,
              srcsecurityzone as srcsecurityzone_4,
              starttime as starttime_4,
              timestamp_baas_internal_sink_process_time as timestamp_baas_internal_sink_process_time_4,
              transprotocol as transprotocol_4,
              vlanid as vlanid_4
       from ods.dwd_tb5
       where ds = cast(
               current_timestamp - INTERVAL '136' DAY as varchar(10)
             )
     ) as t4 on t1.id = t4.id_4
     left join (
       select id as id_5,
              timestamp as timestamp_5,
              catbehavior as catbehavior_5,
              catobject as catobject_5,
              catoutcome as catoutcome_5,
              catsignificance as catsignificance_5,
              cattechnique as cattechnique_5,
              collectorreceipttime as collectorreceipttime_5,
              datasubtype as datasubtype_5,
              datatype as datatype_5,
              destport as destport_5,
              destsecurityzone as destsecurityzone_5,
              devicecat as devicecat_5,
              devicename as devicename_5,
              deviceproducttype as deviceproducttype_5,
              devicereceipttime as devicereceipttime_5,
              devicesendproductname as devicesendproductname_5,
              deviceversion as deviceversion_5,
              direction as direction_5,
              dnstype as dnstype_5,
              endtime as endtime_5,
              etl_engineinfo as etl_engineinfo_5,
              eventcount as eventcount_5,
              eventid as eventid_5,
              interfacename as interfacename_5,
              logsessionid as logsessionid_5,
              logtype as logtype_5,
              machinecode as machinecode_5,
              message as message_5,
              productvendorname as productvendorname_5,
              querytype as querytype_5,
              requestdomain as requestdomain_5,
              severity as severity_5,
              srcgeolatitude as srcgeolatitude_5,
              srcgeolongitude as srcgeolongitude_5,
              srcgeoregion as srcgeoregion_5,
              srcsecurityzone as srcsecurityzone_5,
              starttime as starttime_5,
              timestamp_baas_internal_sink_process_time as timestamp_baas_internal_sink_process_time_5,
              transprotocol as transprotocol_5,
              vlanid as vlanid_5
       from ods.dwd_tb5
       where ds = cast(
               current_timestamp - INTERVAL '136' DAY as varchar(10)
             )
     ) as t5 on t1.id = t5.id_5
     left join (
       select id as id_6,
              timestamp as timestamp_6,
              catbehavior as catbehavior_6,
              catobject as catobject_6,
              catoutcome as catoutcome_6,
              catsignificance as catsignificance_6,
              cattechnique as cattechnique_6,
              collectorreceipttime as collectorreceipttime_6,
              datasubtype as datasubtype_6,
              datatype as datatype_6,
              destport as destport_6,
              destsecurityzone as destsecurityzone_6,
              devicecat as devicecat_6,
              devicename as devicename_6,
              deviceproducttype as deviceproducttype_6,
              devicereceipttime as devicereceipttime_6,
              devicesendproductname as devicesendproductname_6,
              deviceversion as deviceversion_6,
              direction as direction_6,
              dnstype as dnstype_6,
              endtime as endtime_6,
              etl_engineinfo as etl_engineinfo_6,
              eventcount as eventcount_6,
              eventid as eventid_6,
              interfacename as interfacename_6,
              logsessionid as logsessionid_6,
              logtype as logtype_6,
              machinecode as machinecode_6,
              message as message_6,
              productvendorname as productvendorname_6,
              querytype as querytype_6,
              requestdomain as requestdomain_6,
              severity as severity_6,
              srcgeolatitude as srcgeolatitude_6,
              srcgeolongitude as srcgeolongitude_6,
              srcgeoregion as srcgeoregion_6,
              srcsecurityzone as srcsecurityzone_6,
              starttime as starttime_6,
              timestamp_baas_internal_sink_process_time as timestamp_baas_internal_sink_process_time_6,
              transprotocol as transprotocol_6,
              vlanid as vlanid_6
       from ods.dwd_tb5
       where ds = cast(
               current_timestamp - INTERVAL '136' DAY as varchar(10)
             )
     ) as t6 on t1.id = t6.id_6;

-- select * from ods.dws_tb5;


drop table IF EXISTS `ods.ads_tb5`;
create table if not EXISTS ods.ads_tb5(
    datasubtype STRING,
    destsecurityzone STRING,
    direction STRING,
    logtype STRING,
    transprotocol STRING,
    mess_num STRING,
    total_id_num STRING,
    max_vlanid STRING,
    min_querytype STRING,
    str_interfacename STRING,
    len_interfacename STRING,
    avg_srcgeolatitude STRING,
    rank_num STRING
)
PARTITIONED BY (`ds` STRING) STORED AS HOLODESK;






set hive.exec.dynamic.partition = true;
set argodb.allow.insert.overwrite = true;
set use.linac = false;

INSERT OVERWRITE TABLE `ods.ads_tb5`
SELECT
    datasubtype,
    destsecurityzone,
    direction,
    logtype,
    transprotocol,
    sum(length(message)) AS mess_num,
    COUNT(DISTINCT id) AS total_id_num,
    max(vlanid) AS max_vlanid,
    min(querytype) AS min_querytype,
    substr(interfacename, 1, 3) AS str_interfacename,
    length(interfacename) AS len_interfacename,
    avg(CAST(coalesce(srcgeolatitude, 0) AS FLOAT)) avg_srcgeolatitude,
    avg(rank_num) rank_num,
	collect_set(ds)[0]
FROM
    (
        SELECT
            *,
            row_number() OVER (
                PARTITION by datasubtype,
                destsecurityzone,
                direction,
                logtype,
                transprotocol
                ORDER BY
                    logsessionid
            ) AS rank_num
        FROM
            ods.dwd_tb5
        WHERE
			ds = cast(current_timestamp - INTERVAL '136' DAY as varchar(10))
    ) AS t
WHERE
    ds = cast(current_timestamp - INTERVAL '136' DAY as varchar(10))
GROUP BY
    datasubtype,
    destsecurityzone,
    direction,
    logtype,
    transprotocol,
    substr(interfacename, 1, 3),
    length(interfacename);



SELECT id,
       "timestamp",
       "catBehavior",
       "catObject",
       "catOutcome",
       "catSignificance",
       "catTechnique",
       cast("collectorReceiptTime" as varchar(20)) collectorReceiptTime,
       "dataSubType",
       "dataType",
       "destPort",
       "destSecurityZone",
       "deviceCat",
       "deviceName",
       "deviceProductType",
       "deviceReceiptTime",
       "deviceSendProductName",
       "deviceVersion",
       direction,
       "dnsType",
       "endTime",
       "etl_engineInfo",
       "eventCount",
       "eventId",
       "interfaceName",
       "logSessionId",
       "logType",
       "machineCode",
       message,
       "productVendorName",
       "queryType",
       "requestDomain",
       severity,
       "srcGeoLatitude",
       "srcGeoLongitude",
       "srcGeoRegion",
       "srcSecurityZone",
       "startTime",
       timestamp_baas_internal_sink_process_time,
       "transProtocol",
       "vlanId",
       cast("collectorReceiptTime" as varchar(10)) ds
FROM public.ods_es_xdr_log_detail_dd
where cast("collectorReceiptTime" as varchar(10)) =
      cast(current_timestamp - interval '136' day as varchar(10))
  and "requestDomain" notnull




select * from ads_job5_t_ttt