select date(timestamp), count(*) from ods_es_xdr_log_detail_dd group by date(timestamp) limit 10

create  table  ods_es_xdr_log_detail_dd
(  id int8 primary key,
    timestamp timestamp,
    "catBehavior" text,
    "catObject" text,
    "catOutcome" text,
    "catSignificance" text,
    "catTechnique" text,
    "collectorReceiptTime" timestamp,
    "dataSubType" text,
    "dataType" text,
    "destPort" text,
    "destSecurityZone" text,
    "deviceCat" text,
    "deviceName" text,
    "deviceProductType" text,
    "deviceReceiptTime" text,
    "deviceSendProductName" text,
    "deviceVersion" text,
    direction text,
    "dnsType" text,
    "endTime" timestamp,
    "etl_engineInfo" text,
    "eventCount" text,
    "eventId" text,
    "interfaceName" text,
    "logSessionId" text,
    "logType" text,
    "machineCode" text,
    message text,
    "productVendorName" text,
    "queryType" text,
    "requestDomain" text,
    severity text,
    "srcGeoLatitude" text,
    "srcGeoLongitude" text,
    "srcGeoRegion" text,
    "srcSecurityZone" text,
    "startTime" timestamp,
    timestamp_baas_internal_sink_process_time timestamp,
    "transProtocol" text,
    "vlanId" text
)